export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_USER = 'GET_ITEMS_USER';
export const GET_FOLLOW_ITEMS = 'GET_FOLLOW_ITEMS';
export const GET_MY_ITEMS = 'GET_MY_ITEMS';
export const ADD_ITEMS = 'ADD_ITEMS';
export const DELETE_ITEMS = 'DELETE_ITEMS';
export const UPDATE_ITEMS= "UPDATE_ITEMS";
export const ITEMS_LOADING ='ITEMS_LOADING';
export const USER_LOADING ='USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCESS = 'LOGOUT_SUCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LIKE = 'LIKE';
export const USER_PROFILE = 'USER_PROFILE';
export const GET_USER ='GET_USER'
export const GET_ALL_USER ='GET_ALL_USER'
export const POSTED ='POSTED'
export const UPDATED ='UPDATED'
export const RESET ='RESET'

